version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: mini2-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ridedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mini2-network

  mongodb:
    image: mongo:latest
    container_name: mini2-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mini2-network

  miniapp:
    build: .
    container_name: mini2-app
    depends_on:
      - postgres
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ridedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@mongodb:27017/ratingdb?authSource=admin
    networks:
      - mini2-network

networks:
  mini2-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: